name: generator

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - uses: actions/checkout@v3
      - name: Update readme of speaking
        uses: linuxsuren/yaml-readme@d746acf13a2cf3fb2c8eeac4b26f95f269d9a904
        env:
          GH_TOKEN: ${{ secrets.GH_SECRETS }}
        with:
          pattern: 'public-speaking/data/*.yaml'
          template: 'public-speaking/README.tpl'
          output: 'public-speaking/README.md'
          username: linuxsuren
          org: linuxsuren
          repo: linuxsuren
          groupby: year
          push: false
      - name: Update readme
        uses: linuxsuren/yaml-readme@d746acf13a2cf3fb2c8eeac4b26f95f269d9a904
        env:
          GH_TOKEN: ${{ secrets.GH_SECRETS }}
        with:
          template: 'README.tpl'
          output: 'README.md'
          username: linuxsuren
          org: linuxsuren
          repo: linuxsuren
